### ISSUE TITLE
zmień readme

### ISSUE THREAD

**Issue by chickeeen** [ProgramistaZpolski/pzplpolitics#9]
zmień readme i nie zamykaj dopóki ja nie skończe pisać AAAAAAAAAAAAAAAAAAAAAAAAAAAAAYDSAODBUSAODSU :AyUIYOSAIUDSAD ASND UASYOD

**Comment by ProgramistaZpolski** [comment]
nei

**Comment by chickeeen** [comment]
KasztanPolitics to najlepszy test polityczny
a nie może być dwóch najlepszych
więc twój może być dobry, ale nie lepszy niż kasztanpolitics
zmieniaj pedale

**Comment by chickeeen** [comment]
asbyyuayt87asuhduisaiulisasaklybasujhkas

dziękuje
